- hosts: myhosts
  remote_user: root
  tasks:
    - name: bla bla
      block:  
      - name: Move bash script folder to host
        copy:
          src: ../Bash script
          dest: ./
      - name: Run the setup script
        shell: bash ./Bash\ script/setup.sh
      always:  
      - name: Clean up script folder
        file:
          path: ./Bash script
          state: absent 

